from collections.abc import Iterator

from typing_extensions import Self

class Response:
    status_code: int
    url: str
    ok: bool

    @property
    def text(self) -> str: ...
    @property
    def content(self) -> bytes: ...
    def json(self, **kwargs: object) -> object: ...
    def iter_lines(
        self, chunk_size: int = ..., decode_unicode: bool = False
    ) -> Iterator[bytes]: ...
    def iter_content(
        self, chunk_size: int = 1, decode_unicode: bool = False
    ) -> Iterator[bytes]: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> None: ...

class Session:
    headers: dict[str, str]
    def get(self, url: str, params: object = None, **kwargs: object) -> Response: ...
    def request(self, method: str, url: str, **kwargs: object) -> Response: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> None: ...

def get(url: str, params: object = None, **kwargs: object) -> Response: ...
def post(url: str, data: object = None, **kwargs: object) -> Response: ...
def request(method: str, url: str, **kwargs: object) -> Response: ...
