from typing import Any
from typing_extensions import Self

class Response:
    status_code: int
    url: str
    ok: bool

    @property
    def text(self) -> str: ...
    @property
    def content(self) -> bytes: ...
    def json(self, **kwargs: Any) -> Any: ...
    def iter_lines(self, chunk_size: int = ..., decode_unicode: bool = False) -> Any: ...
    def iter_content(self, chunk_size: int = 1, decode_unicode: bool = False) -> Any: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> None: ...

class Session:
    headers: dict[str, str]
    def get(self, url: str, params: Any = None, **kwargs: Any) -> Response: ...
    def request(self, method: str, url: str, **kwargs: Any) -> Response: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> None: ...

def get(url: str, params: Any = None, **kwargs: Any) -> Response: ...
def post(url: str, data: Any = None, **kwargs: Any) -> Response: ...
def request(method: str, url: str, **kwargs: Any) -> Response: ...
