PROXY_TYPE_SOCKS4: int
PROXY_TYPE_SOCKS5: int
PROXY_TYPE_HTTP: int
SOCKS4: int
SOCKS5: int
HTTP: int

class ProxyError(OSError): ...
class GeneralProxyError(ProxyError): ...
class ProxyConnectionError(ProxyError): ...
class SOCKS5AuthError(ProxyError): ...
class SOCKS5Error(ProxyError): ...
class SOCKS4Error(ProxyError): ...
class HTTPError(ProxyError): ...

def set_default_proxy(
    proxy_type: int | None = None,
    addr: str | None = None,
    port: int | None = None,
    rdns: bool = True,
    username: str | None = None,
    password: str | None = None,
) -> None: ...
def setdefaultproxy(*args: object, **kwargs: object) -> None: ...
def get_default_proxy() -> tuple[
    int | None, str | None, int | None, bool, str | None, str | None
]: ...
def wrap_module(module: object) -> None: ...
def create_connection(dest_pair: object, **kwargs: object) -> object: ...

class socksocket:
    def setproxy(
        self,
        proxy_type: int | None = None,
        addr: str | None = None,
        port: int | None = None,
        rdns: bool = True,
        username: str | None = None,
        password: str | None = None,
    ) -> None: ...
