import { COMMANDS } from "./cli";

/** Render documentation/CLI.md from the single router table. */
export function renderCliDocs(): string {
  const lines = [
    "# Repository commands",
    "",
    "This file is generated by `bun run gen -- --write --only cli`. Do not hand-edit.",
    "",
    "Use `bun run <command> -- --help` for full flags.",
    "",
  ];
  for (const command of COMMANDS) {
    lines.push(`## \`bun run ${command.name}\``, "", command.description, "");
    if (command.examples.length > 0) {
      lines.push("```sh");
      for (const example of command.examples) {
        lines.push(example);
      }
      lines.push("```", "");
    }
  }
  return lines.join("\n");
}
