/** @deprecated Import from tool/core/repo.ts instead. Thin shim kept for migration. */
export {
  CATALOG_PATH,
  CLI_DOCS_PATH,
  DOCUMENTATION_DIR,
  DOCS_PATH,
  FIXTURES_DIR,
  ICON_DIR,
  ICONS_MANIFEST_PATH,
  INSTALL_DIR,
  PLUGIN_DIR,
  ROOT,
  SCREENSHOT_PATH,
  TEST_DIR,
  TYPESCRIPT_DIRS,
  TYPESCRIPT_GLOBS,
  UPSTREAM_DIR,
  WEBSITE_GLOBS,
  WORKING_DIR,
} from "../tool/core/repo";
