import { PLUGIN_SOURCES_PATH } from "../core/repo";
import { discoverPlugins, pluginId } from "../core/plugins";

/** Render the Bun watch-manifest that imports every plugin as text. */
export function renderPluginSources(ids: string[]): string {
  const lines = [
    "/**",
    " * Generated by `bun run gen`. Do not hand-edit.",
    " *",
    " * Bun's test watcher follows imported files. Importing each plugin as text",
    " * keeps the engines standalone while making bun test --watch rerun the",
    " * repository tests when an engine changes.",
    " */",
  ];
  for (const id of ids) {
    lines.push(`import ${id}Source from "../plugins/${id}.py" with { type: "text" };`);
  }
  lines.push("", "export const PLUGIN_SOURCES = {");
  for (const id of ids) {
    lines.push(`  ${id}: ${id}Source,`);
  }
  lines.push("} as const;", "");
  return lines.join("\n");
}

export async function pluginSourceIds(): Promise<string[]> {
  return (await discoverPlugins()).map(pluginId).sort();
}

export async function writePluginSources(): Promise<void> {
  await Bun.write(PLUGIN_SOURCES_PATH, renderPluginSources(await pluginSourceIds()));
}

export async function checkPluginSources(): Promise<string | null> {
  const expected = renderPluginSources(await pluginSourceIds());
  const file = Bun.file(PLUGIN_SOURCES_PATH);
  if (!(await file.exists()) || (await file.text()) !== expected) {
    return `${PLUGIN_SOURCES_PATH} is out of date; run gen -- --write`;
  }
  return null;
}
